___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [4]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [5]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/natasha/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/natasha/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/natasha/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/natasha/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/natasha/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/natasha/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/natasha/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/natasha/opt/anaconda3/include']
None


Створити вектор з 10 елементів, заповнений одиницями:

In [7]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [10]:
zeroToTen = np.arange(11)
zeroToTen

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [14]:
zeros = np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [18]:
ran = np.random.random(20)
print(np.nonzero(ran))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [22]:
print("Mean" ,np.mean(ran))
print("Median" ,np.median(ran))
print("Standard deviation" ,np.std(ran))

Mean 0.5283521239141796
Median 0.5159167098668671
Standard deviation 0.23859974587569774


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [23]:
A = np.random.random((4,2))
B = np.random.random((2,2))
C = A @ B
C

array([[1.17396813, 0.42570078],
       [1.0581713 , 0.34080325],
       [0.93407793, 0.19290146],
       [0.94472653, 0.31937571]])

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [30]:
vec = np.matrix.flatten(C)
vec[np.argmax(vec)] = 0
vec

array([0.        , 0.42570078, 1.0581713 , 0.34080325, 0.93407793,
       0.19290146, 0.94472653, 0.31937571])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [32]:
a = np.corrcoef(C[0:],C[1:])
a


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

Дано матрицю. Знайти ранг матриці:

In [33]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
rank = np.linalg.matrix_rank(a)
rank

3

Знайти визначник матриці:

In [34]:
determinant = np.linalg.det(a)
determinant

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [36]:
eigen = np.linalg.eig(a)
eigen

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
        -4.56760167-3.20389947j]),
 array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
         -0.31386258+0.47450898j],
        [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
         -0.07049527-0.4090732j ],
        [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
          0.7099444 -0.j        ]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [43]:
from scipy import stats
a = np.random.randint(0,10,50)
my_mode = scipy.stats.mode(a)
my_mode

ModeResult(mode=array([6]), count=array([10]))

Виведіть лише парні числа, що діляться на 5:

In [104]:
a = np.random.randint(0,10,50)
b=a[np.logical_and(a%2==0 , a%5==0)]
print(a,b)

[5 0 1 6 2 5 0 5 8 0 2 2 7 1 9 1 6 3 8 2 8 1 2 3 1 1 7 6 4 0 1 1 0 3 1 7 5
 6 6 0 7 1 8 7 8 4 4 5 4 4] [0 0 0 0 0 0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [112]:
M = np.array([[2,5],[1,-10]])
A = np.array([1,3])
print(np.linalg.solve(M,A))

[ 1.  -0.2]
